[settings]
auto_install = false

[tools]
cocogitto = "7.0.0"
go = "1.26.5"
golangci-lint = "2.12.2"

[tasks."app:serve"]
description = "Run the application"
run = 'go run cmd/app/main.go'

[tasks."app:build"]
description = "Build the application"
env = { CGO_ENABLED = "0" }
run = 'go build -ldflags="-s -w" -o dist/simplebank cmd/app/main.go'

[tasks."compose:dev:up"]
description = "Run docker compose for development"
run = 'docker compose --profile dev up -d --wait --build'

[tasks."compose:dev:down"]
description = "Stop docker compose for development"
run = 'docker compose --profile dev down -v'

[tasks."golangci-lint:fmt"]
description = "Format code with golangci-lint"
run = 'golangci-lint fmt -v ./cmd/...'

[tasks.golangci-lint]
description = "Run golangci-lint"
run = 'golangci-lint run -v ./cmd/...'

[tasks.govulncheck]
description = "Run govulncheck"
run = [
  'go install golang.org/x/vuln/cmd/govulncheck@latest',
  'govulncheck -show verbose ./cmd/...',
]

[tasks."test:unit"]
description = "Run unit tests"
run = 'go test -race -cover -v ./cmd/...'

[tasks."compose:test:up"]
description = "Run docker compose for testing"
run = 'docker compose --profile test up -d --wait'

[tasks."compose:test:down"]
description = "Stop docker compose for testing"
run = 'docker compose --profile test down -v'

[tasks."test:integration"]
description = "Run integration tests"
depends = ["compose:test:up"]
depends_post = ["compose:test:down"]
run = 'go test -race -cover -v ./... -tags=integration'

[tasks."docker:build"]
description = "Build docker image"
run = 'docker buildx build --platform linux/amd64,linux/arm64 -t simplebank:latest --load .'

[tasks."hooks:install"]
description = "Install git hooks"
run = 'cog install-hook --all'

[tasks."sqlc:generate"]
description = "Generate Go code from SQL with sqlc"
run = [
  'go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest',
  'sqlc generate',
]
