// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_throttles.sql

package db

import (
	"context"
	"time"
)

const advanceLoginThrottleAttempt = `-- name: AdvanceLoginThrottleAttempt :one
UPDATE login_throttles
SET attempt_count = CASE
        WHEN login_throttles.window_started_at <
             $1::timestamptz - make_interval(secs => $2::integer)
            THEN 1
        ELSE login_throttles.attempt_count + 1
    END,
    window_started_at = $1::timestamptz,
    blocked_until = CASE
        WHEN login_throttles.window_started_at <
             $1::timestamptz - make_interval(secs => $2::integer)
            THEN NULL
        ELSE login_throttles.blocked_until
    END,
    expires_at = $1::timestamptz +
        make_interval(secs => $3::integer)
WHERE scope = $4
  AND key_hash = $5
RETURNING scope, key_hash, attempt_count, window_started_at, blocked_until, expires_at
`

type AdvanceLoginThrottleAttemptParams struct {
	Now              time.Time `json:"now"`
	WindowSeconds    int32     `json:"window_seconds"`
	RetentionSeconds int32     `json:"retention_seconds"`
	Scope            string    `json:"scope"`
	KeyHash          string    `json:"key_hash"`
}

func (q *Queries) AdvanceLoginThrottleAttempt(ctx context.Context, arg AdvanceLoginThrottleAttemptParams) (LoginThrottle, error) {
	row := q.db.QueryRow(ctx, advanceLoginThrottleAttempt,
		arg.Now,
		arg.WindowSeconds,
		arg.RetentionSeconds,
		arg.Scope,
		arg.KeyHash,
	)
	var i LoginThrottle
	err := row.Scan(
		&i.Scope,
		&i.KeyHash,
		&i.AttemptCount,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredLoginThrottles = `-- name: DeleteExpiredLoginThrottles :execrows
DELETE FROM login_throttles
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredLoginThrottles(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginThrottles, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginThrottle = `-- name: DeleteLoginThrottle :exec
DELETE FROM login_throttles
WHERE scope = $1 AND key_hash = $2
`

type DeleteLoginThrottleParams struct {
	Scope   string `json:"scope"`
	KeyHash string `json:"key_hash"`
}

func (q *Queries) DeleteLoginThrottle(ctx context.Context, arg DeleteLoginThrottleParams) error {
	_, err := q.db.Exec(ctx, deleteLoginThrottle, arg.Scope, arg.KeyHash)
	return err
}

const getLoginThrottlePairForUpdate = `-- name: GetLoginThrottlePairForUpdate :many
SELECT scope, key_hash, attempt_count, window_started_at, blocked_until, expires_at
FROM login_throttles
WHERE (scope = $1 AND key_hash = $2)
   OR (scope = $3 AND key_hash = $4)
ORDER BY scope, key_hash
FOR UPDATE
`

type GetLoginThrottlePairForUpdateParams struct {
	AccountScope   string `json:"account_scope"`
	AccountKeyHash string `json:"account_key_hash"`
	ClientScope    string `json:"client_scope"`
	ClientKeyHash  string `json:"client_key_hash"`
}

func (q *Queries) GetLoginThrottlePairForUpdate(ctx context.Context, arg GetLoginThrottlePairForUpdateParams) ([]LoginThrottle, error) {
	rows, err := q.db.Query(ctx, getLoginThrottlePairForUpdate,
		arg.AccountScope,
		arg.AccountKeyHash,
		arg.ClientScope,
		arg.ClientKeyHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginThrottle{}
	for rows.Next() {
		var i LoginThrottle
		if err := rows.Scan(
			&i.Scope,
			&i.KeyHash,
			&i.AttemptCount,
			&i.WindowStartedAt,
			&i.BlockedUntil,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initializeLoginThrottlePair = `-- name: InitializeLoginThrottlePair :exec
INSERT INTO login_throttles (
    scope,
    key_hash,
    attempt_count,
    window_started_at,
    blocked_until,
    expires_at
)
VALUES (
    $1,
    $2,
    0,
    $3::timestamptz,
    NULL,
    $3::timestamptz + make_interval(secs => $4::integer)
), (
    $5,
    $6,
    0,
    $3::timestamptz,
    NULL,
    $3::timestamptz + make_interval(secs => $4::integer)
)
ON CONFLICT (scope, key_hash) DO NOTHING
`

type InitializeLoginThrottlePairParams struct {
	AccountScope     string    `json:"account_scope"`
	AccountKeyHash   string    `json:"account_key_hash"`
	Now              time.Time `json:"now"`
	RetentionSeconds int32     `json:"retention_seconds"`
	ClientScope      string    `json:"client_scope"`
	ClientKeyHash    string    `json:"client_key_hash"`
}

func (q *Queries) InitializeLoginThrottlePair(ctx context.Context, arg InitializeLoginThrottlePairParams) error {
	_, err := q.db.Exec(ctx, initializeLoginThrottlePair,
		arg.AccountScope,
		arg.AccountKeyHash,
		arg.Now,
		arg.RetentionSeconds,
		arg.ClientScope,
		arg.ClientKeyHash,
	)
	return err
}

const setLoginThrottleBlockedUntil = `-- name: SetLoginThrottleBlockedUntil :one
UPDATE login_throttles
SET blocked_until = GREATEST(
        COALESCE(blocked_until, $1::timestamptz),
        $1::timestamptz
    ),
    expires_at = GREATEST(expires_at, $1::timestamptz)
WHERE scope = $2
  AND key_hash = $3
RETURNING scope, key_hash, attempt_count, window_started_at, blocked_until, expires_at
`

type SetLoginThrottleBlockedUntilParams struct {
	BlockedUntil time.Time `json:"blocked_until"`
	Scope        string    `json:"scope"`
	KeyHash      string    `json:"key_hash"`
}

func (q *Queries) SetLoginThrottleBlockedUntil(ctx context.Context, arg SetLoginThrottleBlockedUntilParams) (LoginThrottle, error) {
	row := q.db.QueryRow(ctx, setLoginThrottleBlockedUntil, arg.BlockedUntil, arg.Scope, arg.KeyHash)
	var i LoginThrottle
	err := row.Scan(
		&i.Scope,
		&i.KeyHash,
		&i.AttemptCount,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.ExpiresAt,
	)
	return i, err
}
