// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_throttles.sql

package db

import (
	"context"
	"time"
)

const deleteExpiredLoginThrottles = `-- name: DeleteExpiredLoginThrottles :execrows
DELETE FROM login_throttles
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredLoginThrottles(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginThrottles, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginThrottle = `-- name: DeleteLoginThrottle :exec
DELETE FROM login_throttles
WHERE scope = $1 AND key_hash = $2
`

type DeleteLoginThrottleParams struct {
	Scope   string `json:"scope"`
	KeyHash string `json:"key_hash"`
}

func (q *Queries) DeleteLoginThrottle(ctx context.Context, arg DeleteLoginThrottleParams) error {
	_, err := q.db.Exec(ctx, deleteLoginThrottle, arg.Scope, arg.KeyHash)
	return err
}

const getLoginThrottle = `-- name: GetLoginThrottle :one
SELECT scope, key_hash, failure_count, window_started_at, blocked_until, expires_at
FROM login_throttles
WHERE scope = $1 AND key_hash = $2
LIMIT 1
`

type GetLoginThrottleParams struct {
	Scope   string `json:"scope"`
	KeyHash string `json:"key_hash"`
}

func (q *Queries) GetLoginThrottle(ctx context.Context, arg GetLoginThrottleParams) (LoginThrottle, error) {
	row := q.db.QueryRow(ctx, getLoginThrottle, arg.Scope, arg.KeyHash)
	var i LoginThrottle
	err := row.Scan(
		&i.Scope,
		&i.KeyHash,
		&i.FailureCount,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.ExpiresAt,
	)
	return i, err
}

const getLoginThrottleSnapshot = `-- name: GetLoginThrottleSnapshot :many
SELECT scope, key_hash, failure_count, window_started_at, blocked_until, expires_at
FROM login_throttles
WHERE (scope = $1 AND key_hash = $2)
   OR (scope = $3 AND key_hash = $4)
`

type GetLoginThrottleSnapshotParams struct {
	AccountScope   string `json:"account_scope"`
	AccountKeyHash string `json:"account_key_hash"`
	ClientScope    string `json:"client_scope"`
	ClientKeyHash  string `json:"client_key_hash"`
}

func (q *Queries) GetLoginThrottleSnapshot(ctx context.Context, arg GetLoginThrottleSnapshotParams) ([]LoginThrottle, error) {
	rows, err := q.db.Query(ctx, getLoginThrottleSnapshot,
		arg.AccountScope,
		arg.AccountKeyHash,
		arg.ClientScope,
		arg.ClientKeyHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginThrottle{}
	for rows.Next() {
		var i LoginThrottle
		if err := rows.Scan(
			&i.Scope,
			&i.KeyHash,
			&i.FailureCount,
			&i.WindowStartedAt,
			&i.BlockedUntil,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementLoginThrottle = `-- name: IncrementLoginThrottle :one
INSERT INTO login_throttles (
    scope,
    key_hash,
    failure_count,
    window_started_at,
    blocked_until,
    expires_at
)
VALUES (
    $1,
    $2,
    1,
    $3::timestamptz,
    NULL,
    $3::timestamptz + make_interval(secs => $4::integer)
)
ON CONFLICT (scope, key_hash) DO UPDATE
SET failure_count = CASE
        WHEN login_throttles.window_started_at <=
             $3::timestamptz - make_interval(secs => $5::integer)
            THEN 1
        ELSE login_throttles.failure_count + 1
    END,
    window_started_at = CASE
        WHEN login_throttles.window_started_at <=
             $3::timestamptz - make_interval(secs => $5::integer)
            THEN $3::timestamptz
        ELSE login_throttles.window_started_at
    END,
    blocked_until = CASE
        WHEN login_throttles.window_started_at <=
             $3::timestamptz - make_interval(secs => $5::integer)
            THEN NULL
        ELSE login_throttles.blocked_until
    END,
    expires_at = $3::timestamptz +
        make_interval(secs => $4::integer)
RETURNING scope, key_hash, failure_count, window_started_at, blocked_until, expires_at
`

type IncrementLoginThrottleParams struct {
	Scope            string    `json:"scope"`
	KeyHash          string    `json:"key_hash"`
	Now              time.Time `json:"now"`
	RetentionSeconds int32     `json:"retention_seconds"`
	WindowSeconds    int32     `json:"window_seconds"`
}

func (q *Queries) IncrementLoginThrottle(ctx context.Context, arg IncrementLoginThrottleParams) (LoginThrottle, error) {
	row := q.db.QueryRow(ctx, incrementLoginThrottle,
		arg.Scope,
		arg.KeyHash,
		arg.Now,
		arg.RetentionSeconds,
		arg.WindowSeconds,
	)
	var i LoginThrottle
	err := row.Scan(
		&i.Scope,
		&i.KeyHash,
		&i.FailureCount,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.ExpiresAt,
	)
	return i, err
}

const setLoginThrottleBlockedUntil = `-- name: SetLoginThrottleBlockedUntil :one
UPDATE login_throttles
SET blocked_until = GREATEST(
        COALESCE(blocked_until, $1::timestamptz),
        $1::timestamptz
    ),
    expires_at = GREATEST(expires_at, $1::timestamptz)
WHERE scope = $2
  AND key_hash = $3
RETURNING scope, key_hash, failure_count, window_started_at, blocked_until, expires_at
`

type SetLoginThrottleBlockedUntilParams struct {
	BlockedUntil time.Time `json:"blocked_until"`
	Scope        string    `json:"scope"`
	KeyHash      string    `json:"key_hash"`
}

func (q *Queries) SetLoginThrottleBlockedUntil(ctx context.Context, arg SetLoginThrottleBlockedUntilParams) (LoginThrottle, error) {
	row := q.db.QueryRow(ctx, setLoginThrottleBlockedUntil, arg.BlockedUntil, arg.Scope, arg.KeyHash)
	var i LoginThrottle
	err := row.Scan(
		&i.Scope,
		&i.KeyHash,
		&i.FailureCount,
		&i.WindowStartedAt,
		&i.BlockedUntil,
		&i.ExpiresAt,
	)
	return i, err
}
