// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint
FROM notifications
WHERE owner = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (owner, account_id, transfer_id, direction, amount, currency, balance)
SELECT a.owner, a.id, t.id, $1, t.amount, a.currency, a.balance
FROM accounts AS a
JOIN transfers AS t ON t.id = $2
WHERE a.id = $3
  AND (
    ($1 = 'sent' AND t.from_account_id = a.id)
    OR ($1 = 'received' AND t.to_account_id = a.id)
  )
RETURNING id, owner, account_id, transfer_id, direction, amount, currency, balance, read_at, created_at
`

type CreateNotificationParams struct {
	Direction  string    `json:"direction"`
	TransferID uuid.UUID `json:"transfer_id"`
	AccountID  uuid.UUID `json:"account_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.Direction, arg.TransferID, arg.AccountID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AccountID,
		&i.TransferID,
		&i.Direction,
		&i.Amount,
		&i.Currency,
		&i.Balance,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, owner, account_id, transfer_id, direction, amount, currency, balance, read_at, created_at
FROM notifications
WHERE owner = $1
  AND (
    NOT $2::boolean
    OR (created_at, id) < (
      $3::timestamptz,
      $4::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListNotificationsParams struct {
	Owner           string    `json:"owner"`
	HasCursor       bool      `json:"has_cursor"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.Owner,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.AccountID,
			&i.TransferID,
			&i.Direction,
			&i.Amount,
			&i.Currency,
			&i.Balance,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNotificationOwner = `-- name: LockNotificationOwner :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockNotificationOwner(ctx context.Context, owner string) error {
	_, err := q.db.Exec(ctx, lockNotificationOwner, owner)
	return err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE owner = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, owner string) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND owner = $2
RETURNING id, owner, account_id, transfer_id, direction, amount, currency, balance, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID    uuid.UUID `json:"id"`
	Owner string    `json:"owner"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.Owner)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AccountID,
		&i.TransferID,
		&i.Direction,
		&i.Amount,
		&i.Currency,
		&i.Balance,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const publishNotification = `-- name: PublishNotification :exec
SELECT pg_notify(
  'balance_notifications',
  json_build_object(
    'id', $1::uuid,
    'owner', $2::text
  )::text
)
`

type PublishNotificationParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	Owner          string    `json:"owner"`
}

func (q *Queries) PublishNotification(ctx context.Context, arg PublishNotificationParams) error {
	_, err := q.db.Exec(ctx, publishNotification, arg.NotificationID, arg.Owner)
	return err
}
