// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	BlockSession(ctx context.Context, id uuid.UUID) (Session, error)
	CountUnreadNotifications(ctx context.Context, owner string) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionForUpdate(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransferBySourceAndIdempotencyKey(ctx context.Context, arg GetTransferBySourceAndIdempotencyKeyParams) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]Transfer, error)
	LockNotificationOwner(ctx context.Context, owner string) error
	MarkAllNotificationsRead(ctx context.Context, owner string) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	PublishNotification(ctx context.Context, arg PublishNotificationParams) error
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	SumOutgoingTransfersSince(ctx context.Context, fromAccountID uuid.UUID) (int64, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
	VerifyUserEmail(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
