// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (from_account_id, to_account_id, amount, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, from_account_id, to_account_id, amount, created_at, idempotency_key
`

type CreateTransferParams struct {
	FromAccountID  uuid.UUID `json:"from_account_id"`
	ToAccountID    uuid.UUID `json:"to_account_id"`
	Amount         int64     `json:"amount"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.IdempotencyKey,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getTransferBySourceAndIdempotencyKey = `-- name: GetTransferBySourceAndIdempotencyKey :one
SELECT id, from_account_id, to_account_id, amount, created_at, idempotency_key FROM transfers
WHERE from_account_id = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetTransferBySourceAndIdempotencyKeyParams struct {
	FromAccountID  uuid.UUID `json:"from_account_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetTransferBySourceAndIdempotencyKey(ctx context.Context, arg GetTransferBySourceAndIdempotencyKeyParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferBySourceAndIdempotencyKey, arg.FromAccountID, arg.IdempotencyKey)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const listTransfersByAccount = `-- name: ListTransfersByAccount :many
SELECT id, from_account_id, to_account_id, amount, created_at, idempotency_key FROM transfers
WHERE from_account_id = $1 OR to_account_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListTransfersByAccountParams struct {
	AccountID  uuid.UUID `json:"account_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByAccount, arg.AccountID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.CreatedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumOutgoingTransfersSince = `-- name: SumOutgoingTransfersSince :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM transfers
WHERE from_account_id = $1 AND created_at >= $2
`

type SumOutgoingTransfersSinceParams struct {
	FromAccountID uuid.UUID `json:"from_account_id"`
	Since         time.Time `json:"since"`
}

func (q *Queries) SumOutgoingTransfersSince(ctx context.Context, arg SumOutgoingTransfersSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumOutgoingTransfersSince, arg.FromAccountID, arg.Since)
	var total int64
	err := row.Scan(&total)
	return total, err
}
